version: '3'

volumes:
  postgres_data: {}
  static_data: {}
  media_data: {}

services:
  web:
    container_name: ${PROJECT_NAME}_web
    depends_on:
      - db
    build: .
    volumes:
      - .:/app/
      - static_data:/app/static/
      - media_data:/app/media/
    env_file: .env
    command: /start
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    restart: always

  db:
    image: postgres:13.4-buster
    container_name: ${PROJECT_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:5.0
    restart: always
